# import needded columns

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder,LabelEncoder,MinMaxScaler,StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression,Lasso,Ridge,SGDRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import  DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,ExtraTreesRegressor,BaggingRegressor,AdaBoostRegressor,VotingRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier,BaggingClassifier,AdaBoostClassifier,VotingClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.naive_bayes import GaussianNB

from sklearn.cluster import KMeans,DBSCAN

from sklearn.metrics import accuracy_score,mean_absolute_error,confusion_matrix,mean_squared_error,classification_report,silhouette_score

from tensorflow.keras.models import Sequential,Model
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping,ReduceLROnPlateau,CSVLogger,ModelCheckpoint

## **Data Representation**

In [53]:
df=pd.read_csv('D:\\PROJECTS\\PROJECT 6\\Titanic-Dataset.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [54]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [55]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [56]:
df.sample()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
725,726,0,3,"Oreskovic, Mr. Luka",male,20.0,0,0,315094,8.6625,NaN,S

In [57]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [58]:
df.values

array([[1, 0, 3, ..., 7.25, nan, 'S'],
       [2, 1, 1, ..., 71.2833, 'C85', 'C'],
       [3, 1, 3, ..., 7.925, nan, 'S'],
       ...,
       [889, 0, 3, ..., 23.45, nan, 'S'],
       [890, 1, 1, ..., 30.0, 'C148', 'C'],
       [891, 0, 3, ..., 7.75, nan, 'Q']], shape=(891, 12), dtype=object)

In [59]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [60]:
df.value_counts()

PassengerId  Survived  Pclass  Name                                                 Sex     Age   SibSp  Parch  Ticket    Fare     Cabin        Embarked
2            1         1       Cumings, Mrs. John Bradley (Florence Briggs Thayer)  female  38.0  1      0      PC 17599  71.2833  C85          C           1
4            1         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)         female  35.0  1      0      113803    53.1000  C123         S           1
7            0         1       McCarthy, Mr. Timothy J                              male    54.0  0      0      17463     51.8625  E46          S           1
11           1         3       Sandstrom, Miss. Marguerite Rut                      female  4.0   1      1      PP 9549   16.7000  G6           S           1
12           1         1       Bonnell, Miss. Elizabeth                             female  58.0  0      0      113783    26.5500  C103         S           1
                                                                                                                                                           ..
872          1         1       Beckwith, Mrs. Richard Leonard (Sallie Monypeny)     female  47.0  1      1      11751     52.5542  D35          S           1
873          0         1       Carlsson, Mr. Frans Olof                             male    33.0  0      0      695       5.0000   B51 B53 B55  S           1
880          1         1       Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)        female  56.0  0      1      11767     83.1583  C50          C           1
888          1         1       Graham, Miss. Margaret Edith                         female  19.0  0      0      112053    30.0000  B42          S           1
890          1         1       Behr, Mr. Karl Howell                                male    26.0  0      0      111369    30.0000  C148         C           1
Name: count, Length: 183, dtype: int64

In [61]:
df.shape

(891, 12)

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## **Data Wrangling**

**Missing Values**

In [63]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [64]:
df.dropna(subset=['Age', 'Embarked','Cabin'],inplace=True)

**DUPLICATED Values**

In [65]:
df.duplicated().sum()

np.int64(0)

## **Exploratory Data Analysis**

#### **Univariate Analysis**

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 183 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  183 non-null    int64
 1   Survived     183 non-null    int64
 2   Pclass       183 non-null    int64
 3   Name         183 non-null    object
 4   Sex          183 non-null    object
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64
 7   Parch        183 non-null    int64
 8   Ticket       183 non-null    object
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object
 11  Embarked     183 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 18.6+ KB

In [67]:
df['Embarked'].value_counts()

Embarked
S    116
C     65
Q      2
Name: count, dtype: int64

In [68]:
plt.figure(figsize=(18,9), facecolor="white")
embarked = df['Embarked'].value_counts()
colors = sns.color_palette('tab10', n_colors=len(embarked))
plt.pie(df['Embarked'].value_counts().values,labels=df['Embarked'].value_counts().index,colors=colors,
                explode=[0.03]*3,autopct='%1.2f%%',shadow=True,radius=0.6,counterclock=True,textprops={'fontsize':16},
        frame=False,rotatelabels=False)
plt.title("pie of Embarked", fontsize=25, pad=50)
plt.tight_layout()
plt.legend(loc='upper right',title='Embarked',title_fontsize=16,labels=['S 63.39%','C 35.52%','Q 1.09%'])
plt.show()

In [69]:
df['Cabin'].value_counts()

Cabin
G6             4
B96 B98        4
C23 C25 C27    4
F33            3
F2             3
              ..
E17            1
A24            1
C50            1
B42            1
C148           1
Name: count, Length: 133, dtype: int64

In [70]:
df['Fare'].describe()

count    183.000000
mean      78.682469
std       76.347843
min        0.000000
25%       29.700000
50%       57.000000
75%       90.000000
max      512.329200
Name: Fare, dtype: float64

In [71]:
# إنشاء نسخة مؤقتة للعرض فقط
df_plot = df.copy()

# تقسيم الـ Fare لمجموعات (bins)
bins = np.linspace(0, df_plot['Fare'].max()+10, 10)
df_plot['Fare_grouped'] = pd.cut(df_plot['Fare'], bins=bins)

# حساب التوزيع وترتيبه تصاعدي
counts = df_plot['Fare_grouped'].value_counts().sort_index()

plt.figure(figsize=(20,14), facecolor="white")

ax = sns.barplot(x=counts.index, y=counts.values, order=counts.index,
                 edgecolor='black', alpha=0.8, color='green', width=0.5)

plt.title("Distribution of Fare", fontsize=30, pad=50)
plt.xlabel("Fare", fontsize=22)
plt.ylabel("Frequency", fontsize=22)

plt.xticks(ticks=range(len(counts.index)),
           labels=[f'{val} $' for val in counts.index],
           rotation=45, fontsize=17)

plt.yticks(range(0,95,5), fontsize=18)
plt.grid(alpha=0.8, color='gray')

# إضافة الأرقام فوق الأعمدة
for g, val in enumerate(counts.values):
    plt.text(g, val+2, str(val), ha='center', fontsize=18)

plt.tight_layout()
plt.show()

In [72]:
df['Ticket'].value_counts()

Ticket
19950       4
113760      4
PC 17572    3
110413      3
PC 17582    3
           ..
17466       1
PC 17590    1
695         1
112053      1
111369      1
Name: count, Length: 127, dtype: int64

In [73]:
df['Parch'].describe()

count    183.000000
mean       0.475410
std        0.754617
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        4.000000
Name: Parch, dtype: float64

In [74]:
df['SibSp'].describe()

count    183.000000
mean       0.464481
std        0.644159
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        3.000000
Name: SibSp, dtype: float64

In [75]:
df['Age'].describe()

count    183.000000
mean      35.674426
std       15.643866
min        0.920000
25%       24.000000
50%       36.000000
75%       47.500000
max       80.000000
Name: Age, dtype: float64

In [76]:
# إنشاء نسخة مؤقتة للعرض فقط
df_plot = df.copy()

# إنشاء مجموعات للأعمار (كل 10 سنوات مثلاً) على النسخة فقط
bins = range(0, int(df_plot['Age'].max())+10, 10)
df_plot['Age_grouped'] = pd.cut(df_plot['Age'], bins=bins)

# حساب التوزيع وترتيبه تصاعدي
counts = df_plot['Age_grouped'].value_counts().sort_index()

plt.figure(figsize=(20,14), facecolor="white")

ax = sns.barplot(x=counts.index, y=counts.values, order=counts.index, width=0.5,
                 edgecolor='black', alpha=0.8, color='blue')

plt.title("Age Distribution", fontsize=30, pad=50)
plt.xlabel("Age", fontsize=22)
plt.ylabel("Count", fontsize=22)

plt.xticks(ticks=range(len(counts.index)),
           labels=[f'{val}' for val in counts.index],
           rotation=45, fontsize=17)

plt.yticks(range(0,50,5), fontsize=18)
plt.grid(alpha=0.8, color='gray')

# إضافة الأرقام فوق الأعمدة
for container in ax.containers:
    ax.bar_label(container, fmt='%d', fontsize=15, padding=2)

plt.tight_layout()
plt.show()

In [77]:
df['Sex'].value_counts()

Sex
male      95
female    88
Name: count, dtype: int64

In [78]:
plt.figure(figsize=(18,9), facecolor="white")
sex = df['Sex'].value_counts()
colors = sns.color_palette('tab10', n_colors=len(sex))
plt.pie(df['Sex'].value_counts().values,labels=df['Sex'].value_counts().index,colors=colors,
                explode=[0.02]*2,autopct='%1.2f%%',shadow=True,radius=0.6,counterclock=True,textprops={'fontsize':16},
        frame=False,rotatelabels=False)
plt.title("pie of Sex", fontsize=25, pad=50)
plt.tight_layout()
plt.legend(loc='upper right',title='Sex',title_fontsize=16,labels=['male 64,76%','female 35.24%'])
plt.show()

In [79]:
df['Name'].value_counts()

Name
Cumings, Mrs. John Bradley (Florence Briggs Thayer)    1
Futrelle, Mrs. Jacques Heath (Lily May Peel)           1
McCarthy, Mr. Timothy J                                1
Sandstrom, Miss. Marguerite Rut                        1
Bonnell, Miss. Elizabeth                               1
                                                      ..
Beckwith, Mrs. Richard Leonard (Sallie Monypeny)       1
Carlsson, Mr. Frans Olof                               1
Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)          1
Graham, Miss. Margaret Edith                           1
Behr, Mr. Karl Howell                                  1
Name: count, Length: 183, dtype: int64

In [80]:
df['Pclass'].describe()

count    183.000000
mean       1.191257
std        0.515187
min        1.000000
25%        1.000000
50%        1.000000
75%        1.000000
max        3.000000
Name: Pclass, dtype: float64

In [81]:
df['Survived'].describe()

count    183.000000
mean       0.672131
std        0.470725
min        0.000000
25%        0.000000
50%        1.000000
75%        1.000000
max        1.000000
Name: Survived, dtype: float64

In [82]:
df['PassengerId'].describe()

count    183.000000
mean     455.366120
std      247.052476
min        2.000000
25%      263.500000
50%      457.000000
75%      676.000000
max      890.000000
Name: PassengerId, dtype: float64

#### **Bivariate Analysis**

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 183 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  183 non-null    int64
 1   Survived     183 non-null    int64
 2   Pclass       183 non-null    int64
 3   Name         183 non-null    object
 4   Sex          183 non-null    object
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64
 7   Parch        183 non-null    int64
 8   Ticket       183 non-null    object
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object
 11  Embarked     183 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 18.6+ KB

# Survived + Pclass

In [84]:
df[['Survived','Pclass']].describe()

         Survived      Pclass
count  183.000000  183.000000
mean     0.672131    1.191257
std      0.470725    0.515187
min      0.000000    1.000000
25%      0.000000    1.000000
50%      1.000000    1.000000
75%      1.000000    1.000000
max      1.000000    3.000000

In [85]:
plt.figure(figsize=(16,10))
ax = sns.countplot(x='Pclass', hue='Survived', data=df, palette='Set1', alpha=0.8,width=0.5)

plt.title('Survival Count by Pclass', fontsize=30, pad=25)
plt.xlabel("Pclass", fontsize=22)
plt.ylabel("Count", fontsize=22)

plt.xticks(fontsize=18)
plt.yticks(range(0,130,10), fontsize=18)
plt.grid(axis='y', alpha=0.8, color='gray')
plt.legend(loc='upper right', title='Survived', title_fontsize=18, fontsize=15)

# إضافة الأرقام فوق الأعمدة
for container in ax.containers:
    ax.bar_label(container, fmt='%d', fontsize=15, padding=3)

plt.tight_layout()
plt.show()

# Survived + Sex

In [86]:
df.groupby(['Survived'])['Sex'].value_counts()

Survived  Sex
0         male      54
          female     6
1         female    82
          male      41
Name: count, dtype: int64

In [87]:
plt.figure(figsize=(16,10))
ax=sns.countplot(x='Sex', hue='Survived', data=df, palette='hls', alpha=0.8,width=0.4)

plt.title('Survival Count by Sex', fontsize=30, pad=25)
plt.xlabel("Sex", fontsize=22)
plt.ylabel("Count", fontsize=22)

plt.xticks(fontsize=18)
plt.yticks(fontsize=18)
plt.grid(axis='y', alpha=0.8, color='gray')
plt.legend(loc='upper right',title='Survived',title_fontsize=18,fontsize=15)
plt.tight_layout()
for container in ax.containers:
    ax.bar_label(container,fmt='%d',fontsize=15,padding=2)
plt.show()

# multivariate analysis

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 183 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  183 non-null    int64
 1   Survived     183 non-null    int64
 2   Pclass       183 non-null    int64
 3   Name         183 non-null    object
 4   Sex          183 non-null    object
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64
 7   Parch        183 non-null    int64
 8   Ticket       183 non-null    object
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object
 11  Embarked     183 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 18.6+ KB

# heatmap numeric values

In [89]:
corr=df[['Survived','Pclass','Age','SibSp','Parch','Fare']].corr

In [90]:
correlation = df.corr(numeric_only=True)
plt.figure(figsize=(20,15))
sns.heatmap(correlation, annot=True, cmap="plasma", linewidths=0.8,annot_kws={'size':18})
plt.title('Correlation Heatmap of Titanic Dataset',fontsize=30,pad=25)
plt.tight_layout()
plt.xticks(fontsize=18)
plt.yticks(fontsize=18)
plt.show()

## **Preprocessing**

#### **Drop Unneeded Columns**

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 183 entries, 1 to 889
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  183 non-null    int64
 1   Survived     183 non-null    int64
 2   Pclass       183 non-null    int64
 3   Name         183 non-null    object
 4   Sex          183 non-null    object
 5   Age          183 non-null    float64
 6   SibSp        183 non-null    int64
 7   Parch        183 non-null    int64
 8   Ticket       183 non-null    object
 9   Fare         183 non-null    float64
 10  Cabin        183 non-null    object
 11  Embarked     183 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 18.6+ KB

In [92]:
df.drop(columns=['PassengerId','Cabin','Name'],inplace=True)

#### **x and y**

In [93]:
x=df.drop('Survived',axis=1)
y=df['Survived']

In [94]:
x

     Pclass     Sex   Age  SibSp  Parch    Ticket     Fare Embarked
1         1  female  38.0      1      0  PC 17599  71.2833        C
3         1  female  35.0      1      0    113803  53.1000        S
6         1    male  54.0      0      0     17463  51.8625        S
10        3  female   4.0      1      1   PP 9549  16.7000        S
11        1  female  58.0      0      0    113783  26.5500        S
..      ...     ...   ...    ...    ...       ...      ...      ...
871       1  female  47.0      1      1     11751  52.5542        S
872       1    male  33.0      0      0       695   5.0000        S
879       1  female  56.0      0      1     11767  83.1583        C
887       1  female  19.0      0      0    112053  30.0000        S
889       1    male  26.0      0      0    111369  30.0000        C

[183 rows x 8 columns]

In [95]:
y

1      1
3      1
6      0
10     1
11     1
      ..
871    1
872    0
879    1
887    1
889    1
Name: Survived, Length: 183, dtype: int64

# label encoder

In [96]:
encoder=LabelEncoder()
x['Sex']=encoder.fit_transform(x['Sex'])
x['Ticket']=encoder.fit_transform(x['Ticket'])
x['Fare']=encoder.fit_transform(x['Fare'])
x['Embarked']=encoder.fit_transform(x['Embarked'])
x['Age']=encoder.fit_transform(x['Age'])

In [97]:
x

     Pclass  Sex  Age  SibSp  Parch  Ticket  Fare  Embarked
1         1    0   32      1      0     109    57         0
3         1    0   28      1      0      31    44         2
6         1    1   49      0      0      55    41         2
10        3    0    4      1      1     120    10         2
11        1    0   53      0      0      26    17         2
..      ...  ...  ...    ...    ...     ...   ...       ...
871       1    0   42      1      1      33    43         2
872       1    1   26      0      0      89     1         2
879       1    0   51      0      1      38    68         0
887       1    0   12      0      0      10    23         2
889       1    1   18      0      0       8    23         0

[183 rows x 8 columns]

In [98]:
y

1      1
3      1
6      0
10     1
11     1
      ..
871    1
872    0
879    1
887    1
889    1
Name: Survived, Length: 183, dtype: int64

# train_test_split

In [99]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=60,test_size=0.2)

In [100]:
print(df.dtypes)

Survived      int64
Pclass        int64
Sex          object
Age         float64
SibSp         int64
Parch         int64
Ticket       object
Fare        float64
Embarked     object
dtype: object

# LogisticRegression

In [101]:
lr=LogisticRegression()
lr.fit(x_train,y_train)

c:\Users\Mega\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [102]:
lr.score(x_train,y_train)

0.7808219178082192

In [103]:
lr.score(x_test,y_test)

0.7027027027027027

In [104]:
y_pred=lr.predict(x_train)
print(mean_absolute_error(y_pred,y_train))

0.2191780821917808

In [105]:
y_pred=lr.predict(x_test)
print(mean_absolute_error(y_pred,y_test))

0.2972972972972973

# DecisionTreeClassifier

In [106]:
tree=DecisionTreeClassifier(criterion='gini',splitter='best',ccp_alpha=0,min_samples_split=2,min_samples_leaf =1,random_state=0,min_impurity_decrease=0)
tree.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0, min_impurity_decrease=0, random_state=0)

In [107]:
tree.score(x_train,y_train)

1.0

In [108]:
tree.score(x_test,y_test)

0.7297297297297297

In [109]:
y_pred=tree.predict(x_train)
print(mean_absolute_error(y_pred,y_train))

0.0

In [110]:
y_pred=tree.predict(x_test)
print(mean_absolute_error(y_pred,y_test))

0.2702702702702703

# KNeighborsClassifier

In [111]:
neighbors=KNeighborsClassifier(n_neighbors=1,leaf_size=60,weights='uniform',algorithm='auto',n_jobs=2,p=50)
neighbors.fit(x_train,y_train)

KNeighborsClassifier(leaf_size=60, n_jobs=2, n_neighbors=1, p=50)

In [112]:
neighbors.score(x_train,y_train)

1.0

In [113]:
neighbors.score(x_test,y_test)

0.5405405405405406

In [114]:
y_pred=neighbors.predict(x_train)
print(mean_absolute_error(y_pred,y_train))

0.0

In [115]:
y_pred=neighbors.predict(x_test)
print(mean_absolute_error(y_pred,y_test))

0.4594594594594595

# SVC

In [116]:
svm=SVC(kernel='rbf',degree=10,gamma='scale',C=1000000,tol=0.0002)
svm.fit(x_train,y_train)

SVC(C=1000000, degree=10, tol=0.0002)

In [117]:
svm.score(x_train,y_train)

1.0

In [118]:
svm.score(x_test,y_test)

0.7837837837837838

In [119]:
y_pred=svm.predict(x_train)
print(mean_absolute_error(y_pred,y_train))

0.0

In [120]:
y_pred=svm.predict(x_test)
print(mean_absolute_error(y_pred,y_test))

0.21621621621621623

RandomForestRegressor,ExtraTreesRegressor,BaggingRegressor,AdaBoostRegressor,VotingRegressor

In [121]:
rf=RandomForestClassifier(n_estimators=1000)
rf.fit(x_train,y_train)

RandomForestClassifier(n_estimators=1000)

In [122]:
rf.score(x_train,y_train)

1.0

In [123]:
rf.score(x_test,y_test)

0.7837837837837838

In [124]:
y_pred=rf.predict(x_train)
print(mean_absolute_error(y_pred,y_train))

0.0

In [125]:
y_pred=rf.predict(x_test)
print(mean_absolute_error(y_pred,y_test))

0.21621621621621623

In [126]:
bag=BaggingClassifier(n_estimators=1000)
bag.fit(x_train,y_train)

BaggingClassifier(n_estimators=1000)

In [127]:
bag.score(x_train,y_train)

1.0

In [128]:
bag.score(x_test,y_test)

0.7567567567567568

In [129]:
y_pred=bag.predict(x_train)
print(mean_absolute_error(y_pred,y_train))

0.0

In [130]:
y_pred=bag.predict(x_test)
print(mean_absolute_error(y_pred,y_test))

0.24324324324324326

In [131]:
ada=AdaBoostClassifier(n_estimators=10000)
ada.fit(x_train,y_train)

AdaBoostClassifier(n_estimators=10000)

In [132]:
ada.score(x_train,y_train)

1.0

In [133]:
ada.score(x_test,y_test)

0.7567567567567568

In [134]:
y_pred=ada.predict(x_train)
print(mean_absolute_error(y_pred,y_train))

0.0

In [135]:
y_pred=ada.predict(x_test)
print(mean_absolute_error(y_pred,y_test))

0.24324324324324326

In [136]:
extra=ExtraTreesClassifier(n_estimators=10000)
extra.fit(x_train,y_train)

ExtraTreesClassifier(n_estimators=10000)

In [137]:
extra.score(x_train,y_train)

1.0

In [138]:
extra.score(x_test,y_test)

0.8108108108108109

In [139]:
y_pred=extra.predict(x_train)
print(mean_absolute_error(y_pred,y_train))

0.0

In [140]:
y_pred=extra.predict(x_test)
print(mean_absolute_error(y_pred,y_test))

0.1891891891891892

In [141]:
vot=VotingClassifier(estimators=[('t1',LogisticRegression()),
                                ('t2',SVC()),
                                ('t3',KNeighborsClassifier()),
                                ('t4',DecisionTreeClassifier()),
                                ('t5',RandomForestClassifier())])
vot.fit(x_train,y_train)

c:\Users\Mega\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

VotingClassifier(estimators=[('t1', LogisticRegression()), ('t2', SVC()),
                             ('t3', KNeighborsClassifier()),
                             ('t4', DecisionTreeClassifier()),
                             ('t5', RandomForestClassifier())])

In [142]:
vot.score(x_train,y_train)

0.8972602739726028

In [143]:
vot.score(x_test,y_test)

0.7567567567567568

In [144]:
y_pred=vot.predict(x_train)
print(mean_absolute_error(y_pred,y_train))

0.10273972602739725

In [145]:
y_pred=vot.predict(x_test)
print(mean_absolute_error(y_pred,y_test))

0.24324324324324326

# xgboost

In [146]:
xgb=XGBClassifier(n_estimators=10000)
xgb.fit(x_train,y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None,
              n_estimators=10000, n_jobs=None, num_parallel_tree=None, ...)

In [147]:
xgb.score(x_train,y_train)

1.0

In [148]:
xgb.score(x_test,y_test)

0.7837837837837838

In [149]:
y_pred=xgb.predict(x_train)
print(mean_absolute_error(y_pred,y_train))

0.0

In [150]:
y_pred=xgb.predict(x_test)
print(mean_absolute_error(y_pred,y_test))

0.21621621621621623

# lightgmb

In [151]:
light=LGBMClassifier(num_leaves=50,importance_type='split',n_estimators=170,learning_rate=0.1)
light.fit(x_train,y_train)

[LightGBM] [Info] Number of positive: 98, number of negative: 48
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000471 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 138
[LightGBM] [Info] Number of data points in the train set: 146, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.671233 -> initscore=0.713766
[LightGBM] [Info] Start training from score 0.713766
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

c:\Users\Mega\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\externals\loky\backend\context.py:131: UserWarning: Could not find the number of physical cores for the following reason:
[WinError 2] The system cannot find the file specified
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "c:\Users\Mega\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\externals\loky\backend\context.py", line 247, in _count_physical_cores
    cpu_count_physical = _count_physical_cores_win32()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Mega\AppData\Local\Programs\Python\Python312\Lib\site-packages\joblib\externals\loky\backend\context.py", line 299, in _count_physical_cores_win32
    cpu_info = subprocess.run(
               ^^^^^^^^^^^^^^^
  File "c:\Users\Mega\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Mega\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\Users\Mega\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

LGBMClassifier(n_estimators=170, num_leaves=50)

In [152]:
light.score(x_train,y_train)

0.9794520547945206

In [153]:
light.score(x_test,y_test)

0.7567567567567568

In [154]:
y_pred=light.predict(x_train)
print(mean_absolute_error(y_pred,y_train))

0.02054794520547945

In [155]:
y_pred=light.predict(x_test)
print(mean_absolute_error(y_pred,y_test))

0.24324324324324326

# DEEP LEARNING

In [156]:
print(x.shape)

(183, 8)

In [157]:
model=Sequential([
    Dense(64,activation='relu',input_dim=8),
    Dense(32,activation='relu'),
    Dense(16,activation='relu'),
    Dense(8,activation='relu'),
    Dense(1,activation='sigmoid')])
model.compile(optimizer=Adam(learning_rate=0.001),loss='binary_crossentropy',metrics=['accuracy'])

c:\Users\Mega\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [158]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           576 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,329 (13.00 KB)

 Trainable params: 3,329 (13.00 KB)

 Non-trainable params: 0 (0.00 B)

In [159]:
import os
os.makedirs(r"C:\Users\Mega\training_logs", exist_ok=True)

logger = CSVLogger(r"C:\Users\Mega\training_logs\training_log.csv", append=True)
weight = ModelCheckpoint(r"C:\Users\Mega\training_logs\model_weights.h5", save_best_only=True)

In [160]:
model.fit(x_train, y_train, epochs=80,validation_split=0.3,callbacks=[earlystop,reducelr,logger,weight])

NameError: name 'earlystop' is not defined

In [ ]:
model.evaluate(x_train,y_train)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6918 - loss: 0.5918

[0.5917924642562866, 0.6917808055877686]

In [ ]:
model.evaluate(x_test,y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7568 - loss: 0.5802

[0.5802106857299805, 0.7567567825317383]